image:node:14.15.0-stretch
stages:
  - build
  - test

Install_dependencies:
  stage: build
  script: 
    - yarn install
  cache:
    paths:
      - node_modules
  key:
    files:
      - yarn.lock
      
run_test:
  stage: test
  script: CI=true yarn test
