image: node:14.15.0-stretch
stages:
  - build
  - test

Install_dependencies:
  stage: build
  script: 
    - yarn install
    - yarn build
  artifacts:
    paths:
      - node_modules
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

run_test:
  stage: test
  script: CI=true yarn test

run_linter:
  stage: test
  script: yarn run eslint src/**.js
 
test:
  stage: deploy
  script:
    - cp -r build /www/test-app/$CI_COMMIT_SHA
    - ln -fsnv /var/www/test-app/$CI_COMMIT_SHA /www/html